package by.epam.web.controller.command;

/**
 * This class consist of an enumeration of command names
 * */

public enum CommandName {
	ACCEPTORDER,
	ADDNEWCAR,
	AUTHORIZATION,
	CANCELORDER,
	CHANGEPASSWORD,
	CHANGEPD,
	COMPLETEORDER,
	CREATEORDER,
	DELETECAR,
	EDITCAR,
	ERROR404,
	ERROR500,
	GOTOACCOUNT,
	GOTOADDNEWCAR,
	GOTOCAR,
	GOTOCARSBASE,
	GOTOCHANGEPASSWORD,
	GOTOCHANGEPD,
	GOTOEDITCAR,
	GOTOORDERHISTORY,
	GOTOPERSONALDATA,
	GOTOREGISTRATION,
	GOTOSIGNIN,
	GOTOVERIFICATIONPAGE,
	LOCAL,
	LOGOUT,
	MAINPAGE,
	MAINPAGEWITHDATEUSER,
	MAINPAGEWITHFILTER,
	REGISTRATION,
	SUCCESSCHANGE,
	SUCCESSREGISTRATION;
}
